#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 03, 2022 12:28:28 PM CST  platform: Linux
#    Mar 04, 2022 03:27:06 AM CST  platform: Linux
#    Mar 04, 2022 04:10:00 AM CST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import demo1

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = demo1.Main(_top1)
    startup()
    root.mainloop()

def startup():
    _w1.Checkbutton1.invoke()
    _w1.Radiobutton1.invoke()
    _w1.Radiobutton3.invoke()
    _w1.Radiobutton3.config(relief=FLAT)
    _w1.Radiobutton4.config(relief=FLAT)

def on_chkbtnClick(*args):
    print('demo1_support.on_chkbtnClick')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    status_list = ['Off', 'ON']
    cb1 = _w1.che47.get()
    cb2 = _w1.che48.get()
    cb3 = _w1.che49.get()
    cb4 = _w1.che50.get()
    _w1.CheckDisplay.set(
        f'{status_list[cb1]} - {status_list[cb2]} - {status_list[cb3]} - {status_list[cb4]}'
    )

def on_rbtnClick1(*args):
    print('demo1_support.on_rbtnClick1')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    which1 = _w1.selectedButton.get()
    _w1.RadioDisplay.set(f'Normal RB {which1} Selected')

def on_rbtnClick2(*args):
    print('demo1_support.on_rbtnClick2')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    _w1.Radiobutton3.config(relief=FLAT)
    _w1.Radiobutton4.config(relief=FLAT)

    which2 = _w1.selectedButton2.get()

    _w1.RadioDisplay.set(f'Special Rb {which2} Selected')

def on_btnExit(*args):
    print('demo1_support.on_btnExit')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    root.destroy()

if __name__ == '__main__':
    demo1.start_up()





