#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Mar 04, 2022 03:29:54 PM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    switchoff75_png "./images/switchoff75.png" 
    switchon75_png "./images/switchon75.png" 
    rbdotunselected20_png "./images/RbDotUnselected20.png" 
    rbdotselected20_png "./images/RbDotSelected20.png" 
    rbdotunselected20_png "./images/RbDotUnselected20.png" 
    rbdotselected20_png "./images/RbDotSelected20.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 914x730+541+363
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Demo 1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -labelanchor n -text Checkbuttons \
        -background $vTcl(actual_gui_bg) -height 285 -highlightcolor black \
        -width 370 
    vTcl:DefineAlias "$top.lab46" "Labelframe1" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.lab46
    checkbutton $site_3_0.che47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_chkbtnClick \
        -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Check 1} -variable che47 
    vTcl:DefineAlias "$site_3_0.che47" "Checkbutton1" vTcl:WidgetProc "Main" 1
    checkbutton $site_3_0.che48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_chkbtnClick \
        -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Check 2} -variable che48 
    vTcl:DefineAlias "$site_3_0.che48" "Checkbutton2" vTcl:WidgetProc "Main" 1
    checkbutton $site_3_0.che49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_chkbtnClick \
        -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image switchoff75_png -indicatoron 0 -justify left \
        -selectimage switchon75_png -variable che49 
    vTcl:DefineAlias "$site_3_0.che49" "Checkbutton3" vTcl:WidgetProc "Main" 1
    checkbutton $site_3_0.che50 \
        -activebackground coral -activeforeground black -background coral \
        -command on_chkbtnClick -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor limegreen -text {Sticky Button} \
        -variable che50 
    vTcl:DefineAlias "$site_3_0.che50" "Checkbutton4" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief groove \
        -text Label -textvariable CheckDisplay 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "Main" 1
    place $site_3_0.che47 \
        -in $site_3_0 -x 30 -y 50 -width 187 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che48 \
        -in $site_3_0 -x 30 -y 80 -width 187 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che49 \
        -in $site_3_0 -x 30 -y 120 -width 79 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che50 \
        -in $site_3_0 -x 30 -y 160 -width 187 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 10 -y 230 -width 349 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab51 \
        \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -labelanchor n -text Radiobuttons \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$top.lab51" "Labelframe2" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.lab51
    radiobutton $site_3_0.rad52 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbtnClick1 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text {Radio 1} -value 1 \
        -variable selectedButton 
    vTcl:DefineAlias "$site_3_0.rad52" "Radiobutton1" vTcl:WidgetProc "Main" 1
    radiobutton $site_3_0.rad53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbtnClick1 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text {Radio 2} -value 2 \
        -variable selectedButton 
    vTcl:DefineAlias "$site_3_0.rad53" "Radiobutton2" vTcl:WidgetProc "Main" 1
    radiobutton $site_3_0.rad54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbtnClick2 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image rbdotunselected20_png -indicatoron 0 \
        -justify left -offrelief flat -padx 5 -selectcolor #d9d9d9 \
        -selectimage rbdotselected20_png -text {Radio 3} -value 3 \
        -variable selectedButton2 
    vTcl:DefineAlias "$site_3_0.rad54" "Radiobutton3" vTcl:WidgetProc "Main" 1
    radiobutton $site_3_0.rad55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbtnClick2 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image rbdotunselected20_png -indicatoron 0 \
        -justify left -offrelief flat -padx 5 -selectcolor #d9d9d9 \
        -selectimage rbdotselected20_png -text {Radio 4} -value 4 \
        -variable selectedButton2 
    vTcl:DefineAlias "$site_3_0.rad55" "Radiobutton4" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief groove \
        -text Label -textvariable RadioDisplay 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "Main" 1
    place $site_3_0.rad52 \
        -in $site_3_0 -x 40 -y 40 -width 238 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad53 \
        -in $site_3_0 -x 40 -y 70 -width 238 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad54 \
        -in $site_3_0 -x 40 -y 120 -width 228 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad55 \
        -in $site_3_0 -x 40 -y 160 -width 228 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 230 -width 349 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnExit \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but46" "btnExit" vTcl:WidgetProc "Main" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 30 -y 30 -width 370 -relwidth 0 -height 285 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 400 -y 30 -width 370 -relwidth 0 -height 285 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 790 -y 20 -width 93 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

